services:
  server:
    build:
      context: ./server
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/app/src
      - ./server/tests:/app/test
    env_file:
      - ./server/.env
    container_name: server
    restart: always
