version: "3.9"

services:
  server:
    image: mikailis/cavalry-guilds:server
    ports:
      - "6000:5000"
    env_file:
      - .env
    container_name: server
    restart: always
    networks:
      - cg-network
  client:
    image: mikailis/cavalry-guilds:client
    ports:
      - "7000:5000"
    env_file:
      - .env
    container_name: client
    restart: always
    networks:
      - cg-network
    depends_on:
      - server

networks:
  cg-network:
    driver: bridge
